### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by hoseinmrdi** [liodali/osm_flutter#3] opened 2020-04-25 08:08 UTC
java.lang.IndexOutOfBoundsException: Index: 262, Size: 262
E/AndroidRuntime(16855): 	at java.util.ArrayList.get(ArrayList.java:437)
E/AndroidRuntime(16855): 	at hamza.dali.flutter_osm_plugin.FlutterRoad.drawEndPoint(FlutterRoad.java:33)
E/AndroidRuntime(16855): 	at hamza.dali.flutter_osm_plugin.FlutterRoad.drawRoad(FlutterRoad.java:49)
E/AndroidRuntime(16855): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView$4.onPostExecute(FlutterOsmView.java:493)
E/AndroidRuntime(16855): 	at hamza.dali.flutter_osm_plugin.FlutterOsmView$4.onPostExecute(FlutterOsmView.java:467)
E/AndroidRuntime(16855): 	at android.os.AsyncTask.finish(AsyncTask.java:695)
E/AndroidRuntime(16855): 	at android.os.AsyncTask.access$600(AsyncTask.java:180)
E/AndroidRuntime(16855): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
E/AndroidRuntime(16855): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(16855): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(16855): 	at android.app.ActivityThread.main(ActivityThread.java:7091)
E/AndroidRuntime(16855): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16855): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/AndroidRuntime(16855): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

**Comment by liodali** [comment] 2020-04-25 09:12
the problem is fixed now.
you can check it

**Closed** 2020-04-25 20:11 UTC
